export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const GET_QUOTE_OF_THE_DAY = 'GET_QUOTE_OF_THE_DAY';
export const SEARCH_QUOTES = 'SEARCH_QUOTES';
export const FAVORITE_QUOTE = 'FAVORITE_QUOTE';
export const UNFAVORITE_QUOTE = 'UNFAVORITE_QUOTE';
export const HIDE_QUOTE = 'HIDE_QUOTE';
